// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Retorna o status de saúde da aplicação, conectividade com o banco de dados Postgres, cache Redis e informações de versão do build.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Verificar saúde da API",
                "responses": {
                    "200": {
                        "description": "API operacional e banco conectado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Banco de dados ou Redis indisponível",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/agent/chat": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Envia uma mensagem para o Agente de IA, permitindo agendar jobs, testar cURLs, consultar histórico ou gerenciar tarefas por linguagem natural.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Agent"
                ],
                "summary": "Conversar com o Agente de IA do CronFlow",
                "parameters": [
                    {
                        "description": "Histórico e nova mensagem do usuário",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AgentChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resposta do Agente de IA e histórico atualizado",
                        "schema": {
                            "$ref": "#/definitions/handler.AgentChatResponse"
                        }
                    },
                    "400": {
                        "description": "Payload inválido ou sem mensagem",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erros na API do Gemini/Groq ou durante a execução de ferramentas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/forgot-password": {
            "post": {
                "description": "Envia um link de recuperação de senha por e-mail (Mockado nos logs do console em desenvolvimento).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Solicitar redefinição de senha",
                "parameters": [
                    {
                        "description": "E-mail do usuário",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "E-mail enviado ou simulado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Autentica um usuário usando e-mail e senha, retornando os tokens JWT e a lista de projetos associados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Realizar login",
                "parameters": [
                    {
                        "description": "Credenciais de login",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Autenticado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "E-mail ou senha ausentes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Credenciais inválidas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno de autenticação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/reset-password": {
            "post": {
                "description": "Valida o token recebido por e-mail e atualiza a senha do usuário.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Redefinir senha com token",
                "parameters": [
                    {
                        "description": "Token de redefinição e nova senha",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Senha redefinida com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/signup": {
            "post": {
                "description": "Cria uma conta de usuário com e-mail, senha, nome completo e CPF, inicializando um projeto padrão e uma chave de API segura.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Registrar uma nova conta de desenvolvedor",
                "parameters": [
                    {
                        "description": "Dados de cadastro contendo e-mail, senha, nome completo, CPF e nome do projeto inicial",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Conta criada, projeto inicializado e chaves geradas",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "E-mail, senha, nome do projeto, nome completo ou CPF ausentes, ou CPF matematicamente inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "E-mail ou CPF já cadastrados por outro usuário",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno de banco ou geração de chaves",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/executions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna a lista paginada de todas as execuções ocorridas nos Jobs do projeto autenticado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Executions"
                ],
                "summary": "Listar execuções globais do Projeto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número da página (padrão 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página (1-100, padrão 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados paginados contendo data ([]execution.ProjectExecution), total, page, limit",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar execuções globais",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/jobs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna todos os agendamentos de Jobs do projeto autenticado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Listar Jobs",
                "responses": {
                    "200": {
                        "description": "Lista de jobs do projeto",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/job.Job"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao listar jobs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria um novo agendamento de Job para o projeto autenticado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Criar Job",
                "parameters": [
                    {
                        "description": "Dados para criação do Job (name, schedule, url, etc.)",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Job criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/job.Job"
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos ou corpo incorreto",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "API Key não fornecida ou inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Limite de jobs do plano atingido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/jobs/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna os detalhes de um Job específico pelo ID, desde que pertença ao projeto autenticado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Buscar Job por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Job",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalhes do job",
                        "schema": {
                            "$ref": "#/definitions/job.Job"
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Acesso negado ao job de outro projeto",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Job não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar job",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Altera os campos configuráveis de um Job (nome, cron, url, etc.).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Atualizar Configurações do Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Job",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos do Job a serem atualizados",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Job atualizado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/job.Job"
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Job não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao atualizar job",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove um Job do banco de dados e limpa os agendamentos associados.",
                "tags": [
                    "Jobs"
                ],
                "summary": "Excluir Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Job",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Job deletado com sucesso"
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Job não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao deletar job",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Altera o status do Job entre 'active' e 'paused'.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Atualizar Status do Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Job",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status (active ou paused)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Status atualizado com sucesso"
                    },
                    "400": {
                        "description": "Status inválido ou corpo incorreto",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Job não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao atualizar status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/jobs/{id}/executions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna a lista de tentativas de execução recentes de um Job específico.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Executions"
                ],
                "summary": "Listar execuções de um Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Job",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limite de resultados (1-200, padrão 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de execuções",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/execution.Execution"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Job não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar execuções",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/jobs/{id}/trigger": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Enfileira a execução de um Job de forma manual e imediata, enviando para o processamento em background.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Disparar Job Imediatamente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Job",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execução manual enfileirada com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Acesso negado ao job de outro projeto",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Job não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno ao enfileirar execução",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/keys": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna os metadados de todas as chaves de API ativas no projeto (id, prefixo, data de criação). O segredo em texto claro nunca é retornado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Listar API Keys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/postgres.APIKey"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Gera uma nova chave de API para o projeto. O segredo em texto claro é retornado apenas nesta chamada. Guarde-o em local seguro.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Criar API Key",
                "responses": {
                    "200": {
                        "description": "Nova chave criada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/keys/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Revoga e exclui definitivamente uma chave de API pelo ID. Ela não poderá mais ser usada para autenticação.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API Keys"
                ],
                "summary": "Revogar/Deletar API Key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da chave de API",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chave revogada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/pix/qr": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna a string do QR Code no formato Data URI Base64 e o payload copia-e-cola correspondente para a chave Pix especificada e o valor solicitado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PIX Apoio"
                ],
                "summary": "Gerar QR Code PIX Dinâmico",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valor da doação (ex: 1.50, padrão 1.00)",
                        "name": "valor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR Code base64 e payload copia-e-cola",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao computar QR Code ou payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/pix/valores": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna as opções rápidas e sugeridas de valores para fazer uma doação de apoio via PIX.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PIX Apoio"
                ],
                "summary": "Listar valores sugeridos para apoio PIX",
                "responses": {
                    "200": {
                        "description": "Opções sugeridas de apoio",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.SugestaoValor"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autenticado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "execution.Execution": {
            "type": "object",
            "properties": {
                "attempt_number": {
                    "type": "integer"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "http_status": {
                    "description": "*int para permitir valor nil, omite o campo se for nil",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "response_body": {
                    "description": "truncado em 2KB",
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/execution.Status"
                },
                "triggered_at": {
                    "type": "string"
                }
            }
        },
        "execution.Status": {
            "type": "string",
            "enum": [
                "success",
                "failed",
                "timeout"
            ],
            "x-enum-varnames": [
                "StatusSuccess",
                "StatusFailed",
                "StatusTimeout"
            ]
        },
        "handler.AgentChatRequest": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.GeminiMessage"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "crie um job para rodar a cada 5 minutos batendo em https://httpbin.org/get"
                }
            }
        },
        "handler.AgentChatResponse": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.GeminiMessage"
                    }
                },
                "reply": {
                    "type": "string",
                    "example": "Executando ferramenta createJob... Job criado com ID 4a82 com sucesso! 🚀"
                }
            }
        },
        "handler.AuthResponse": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ProjectResponse"
                    }
                },
                "token": {
                    "$ref": "#/definitions/handler.TokenResponse"
                },
                "user": {
                    "$ref": "#/definitions/handler.UserResponse"
                }
            }
        },
        "handler.ForgotPasswordRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "handler.GeminiFunctionCall": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handler.GeminiFunctionResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "handler.GeminiMessage": {
            "type": "object",
            "properties": {
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.GeminiPart"
                    }
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "handler.GeminiPart": {
            "type": "object",
            "properties": {
                "functionCall": {
                    "$ref": "#/definitions/handler.GeminiFunctionCall"
                },
                "functionResponse": {
                    "$ref": "#/definitions/handler.GeminiFunctionResponse"
                },
                "text": {
                    "type": "string"
                },
                "thoughtSignature": {
                    "type": "string"
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.ProjectResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "handler.SignupRequest": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                }
            }
        },
        "handler.SugestaoValor": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "valor": {
                    "type": "string"
                }
            }
        },
        "handler.TokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresIn": {
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "tokenType": {
                    "type": "string"
                }
            }
        },
        "handler.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "plan": {
                    "type": "string"
                }
            }
        },
        "job.HTTPMethod": {
            "type": "string",
            "enum": [
                "GET",
                "POST"
            ],
            "x-enum-varnames": [
                "MethodGet",
                "MethodPost"
            ]
        },
        "job.Job": {
            "type": "object",
            "properties": {
                "consecutive_failures": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "headers": {
                    "description": "{\"Content-Type\": \"application/json\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "http_method": {
                    "$ref": "#/definitions/job.HTTPMethod"
                },
                "id": {
                    "type": "string"
                },
                "last_run_at": {
                    "description": "se nunca rodou, é nil",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "next_job_id": {
                    "type": "string"
                },
                "next_run_at": {
                    "type": "string"
                },
                "payload": {
                    "description": "corpo JSON",
                    "type": "object",
                    "additionalProperties": {}
                },
                "project_id": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/job.Status"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timezone": {
                    "description": "\"AMERICA/Sao_Paulo\", \"UTC\", etc",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "webhook_alert_url": {
                    "description": "URL para callbacks de sucesso/falha",
                    "type": "string"
                }
            }
        },
        "job.Status": {
            "type": "string",
            "enum": [
                "active",
                "paused",
                "failing"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusPaused",
                "StatusFailing"
            ]
        },
        "postgres.APIKey": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Tipo \"Bearer \u003csua-api-key\u003e\" para se autenticar.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CronFlow API",
	Description:      "API do sistema CronFlow para agendamento e monitoramento de execução de tarefas distribuídas em background.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
